server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
file:
  upload-dir: "src/main/resources/static/images"
jwt:
  signerKey: "fKe+ZH6xJYwTNSr0wrrbPMMWDvJOOKe3CP9CnefTMfGyf4GByGLSgmFwgc/Gr9T1"
  valid-duration: 3600
  refreshable-duration: 6000
