server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "fKe+ZH6xJYwTNSr0wrrbPMMWDvJOOKe3CP9CnefTMfGyf4GByGLSgmFwgc/Gr9T1"
  valid-duration: 3600
  refreshable-duration: 6000